import { useMemo } from 'react'
import { getStageColor } from '../../lib/beltColors'
import {
  buildCalendarMonths,
  groupSessionsByDay,
  isSameDay,
  toDateKey,
} from '../../lib/calendarGrid'
import { CalendarDayCell } from '../../features/calendar/CalendarDayCell'
import { DemoStreakBar } from '../DemoStreakBar'
import { buildDemoYear } from '../demo/demoYear'

const WEEKDAY_INITIALS = ['S', 'M', 'T', 'W', 'T', 'F', 'S'] as const
const MONTHS_BACK = 11

/**
 * An illustrated year, not a claim about anyone's real history. The sessions are generated
 * by running the app's own progression rules, so the belt colors, the mid-year slump, and
 * the stage the year ends on are all consequences of `mastery.ts` rather than decoration.
 */
export function CalendarSection() {
  const { sessions, progress, finalStreak, months, sessionsByDay, today } = useMemo(() => {
    const now = new Date()
    now.setHours(0, 0, 0, 0)
    const year = buildDemoYear(now)

    return {
      ...year,
      months: buildCalendarMonths(MONTHS_BACK, 0),
      sessionsByDay: groupSessionsByDay(year.sessions),
      today: now,
    }
  }, [])

  const stageMinutes = progress.currentStageMinutes

  return (
    <section className="mx-auto w-full max-w-6xl px-6 py-24">
      <p className="text-xs uppercase tracking-widest text-white/40">The record</p>
      <h2 className="mt-4 text-3xl font-semibold text-white sm:text-4xl">
        One distracted session resets the streak.
      </h2>
      <p className="mt-5 max-w-2xl text-base leading-relaxed text-white/60">
        Every completed session shades a day. The color is the longest session you finished
        that day; the opacity is how much of it you finished undistracted. Nothing is ever
        erased, and the ladder never runs backwards.
      </p>

      <div className="glass-card mt-12 rounded-glass-lg p-6 sm:p-8">
        <div className="flex flex-wrap items-end justify-between gap-6 border-b border-white/10 pb-5">
          <div>
            <p className="text-[10px] uppercase tracking-widest text-white/40">Focus level</p>
            <p className="text-xl font-light" style={{ color: getStageColor(stageMinutes) }}>
              {stageMinutes} min
            </p>
          </div>
          <div className="w-full max-w-[12rem]">
            <DemoStreakBar streak={finalStreak} stageMinutes={stageMinutes} />
          </div>
        </div>

        <div className="mt-8 grid grid-cols-2 gap-x-6 gap-y-8 sm:grid-cols-3 lg:grid-cols-4">
          {months.map((month) => (
            <div key={`${month.year}-${month.month}`}>
              <p className="mb-2 text-xs font-medium text-white/70">
                {month.label} <span className="text-white/35">{month.year}</span>
              </p>
              <div className="mb-1 grid grid-cols-7 gap-1 text-[9px] text-white/30">
                {WEEKDAY_INITIALS.map((initial, index) => (
                  <div key={`${initial}-${index}`} className="text-center">
                    {initial}
                  </div>
                ))}
              </div>
              <div className="grid grid-cols-7 gap-1">
                {month.weeks.flatMap((week, weekIndex) =>
                  week.map((day, dayIndex) => {
                    if (!day) {
                      return (
                        <div
                          key={`${month.year}-${month.month}-${weekIndex}-${dayIndex}`}
                          className="aspect-square min-h-0 min-w-0"
                          aria-hidden="true"
                        />
                      )
                    }

                    const dateKey = toDateKey(day)
                    return (
                      <CalendarDayCell
                        key={dateKey}
                        date={day}
                        sessions={sessionsByDay.get(dateKey) ?? []}
                        isToday={isSameDay(day, today)}
                        isPlannerClickable={false}
                      />
                    )
                  }),
                )}
              </div>
            </div>
          ))}
        </div>

        <p className="mt-8 border-t border-white/10 pt-5 text-[11px] leading-relaxed text-white/40">
          An illustrated year of progression — {sessions.length} sessions generated by the
          app&rsquo;s own advancement rules, not a record of anyone&rsquo;s real focus history.
        </p>
      </div>
    </section>
  )
}
